### ISSUE TITLE
New version of slideshow module

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/slideshow#4]
anybody interested with this module? 

 Im currently trying to update this great module. Still work in progress 
https://github.com/liomj/slideshow

**Comment by mambax7** [comment]
Since you're working on it, I'll move it to the main repository: XoopsModules25x
You won't have to do anything - GitHub should redirect you there automatically

**Comment by liomj** [comment]
thank you mamba..i guess we should also move countdown to the main repository

**Comment by mambax7** [comment]
Done: https://github.com/XoopsModules25x/countdown
